### ISSUE TITLE
Unable to determine the disk for widget Backend\FormWidgets\MarkdownEditor" on line 166

### ISSUE THREAD

**Issue by bkrajendra** [wintercms/wn-driveraws-plugin#3]
I'm using a fresh instance of Winter CMS 1.21
Need to configure AWS SES in mail config. All is working ok.
But when I go to template configuration in mail settings. I am getting this error:
```
"Unable to determine the disk for widget Backend\FormWidgets\MarkdownEditor" on line 166 of D:\...\plugins\winter\driveraws\behaviors\StreamS3Uploads.php
```

**Comment by LukeTowers** [comment]
@bkrajendra try commenting out https://github.com/wintercms/wn-driveraws-plugin/blob/main/Plugin.php#L154 and see if that solves the issue.

**Comment by hirisov** [comment]
I can confirm this bug, the same happens in my installation with the dev-main branch of this plugin. Commenting out the L154 "fixes" the problem.

**Comment by bkrajendra** [comment]
@LukeTowers I was able to resolve it with your solution.
